//.7_Calculate the average of the numbers in an array  of numbers............

var array = [12, 50, 45, 20, 13, 80];//it is the an array...........
let sum = 0;//store a new value ............
//....loop will be start fron 0 and i is less than (<)array of length...........
for (var i = 0; i < array.length; i++) {
    //....will add array index value in sum variable.............
    sum += array[i];
}
//....x is a new variable and sum divided by array of length.............
var x=(sum/array.length)
//...print the value of x.................
console.log(x)
document.write(`<h1> Average number of the array :- ${x} </h1>`);
//....print the value of sum...............ar.............
console.log(sum);
document.write(`<h1> Total sum of the array number :- ${sum} </h1>`);
