//..Create a funcation to calculate  the sum of all the number in a jagged array.........
//.....(array contains number or other array of number on a unlimited number of leves)..............ar.....
var ar =[1,2,[10,[20],[10,5]],[500],[100]];//an array............
function SumValue (ar){//it is the funcation...............
    var sum =0;//sum is the variable...........
    for(var x of ar){
    if( Array .isArray(x)){
        x=SumValue(x);
    }
    sum += x;
}
return sum;//final output............
}
console.log(SumValue(ar));