//...Print all even number from 0--10;..................ar............
//.. loop will be start from 0and last 10.......
for(var i =0;i<=10;i++){
   //...if i divided by 2 fully........
   if (i%2==0){
      //then print the value of i......
    document.write(i);
    document.write("<br>");
   }
}

