//...Create a function that will receive two arrays and will return an array with elements that are in the first
//  array but not in the second Array...........................................
var ar = [1, 2, 3, 4, 8, 6, 9,5, 7];//first array...........
document.getElementById('ar1').innerHTML += ar;//show ar in html page..........
var ar1 = [10, 50, 2, 3, 8, 9, 56]//Second Array....................
document.getElementById('ar2').innerHTML += ar1;//..show ar1 in html page...................
var shortedArry = [];


for (var i = 0; i < ar.length; i++) {

   var isAvailable=false;
    for (var x = 0; x < ar1.length; x++) {
        if (ar[i] === ar1[x]) {//check the condition if ar index equal ar1 x............
            isAvailable=true;//then return true...............
            break;//break statement......................
        }
        
    }
    if(!isAvailable){//check the condition if not isAvailable.............
        shortedArry.push(ar[i]);//then push in ar i.....................
    }
}



 document.getElementById('result').innerHTML += shortedArry;//return for result in HTML page.........

console.log(shortedArry+'shorted array');