//...Find the maximum number in an array of numbers...........ar............

let array =[20,90,41,586,584,585,78,10]//it is the array.............
let maximum =array[0];//store new value of array.........

//loop will be start from 1 and i is less than array of length ..............
for (var i=1;i<array.length;i++){
    //check the value if array index is grater then maximum... 
    if(array[i] > maximum){
        //it store new value in maximum from array............ 
        maximum=array[i];
      
    }
}
//return the final result......
console.log(maximum);
document.write(`<h1> Maximum number of array :- ${maximum}`)


//jkhgfgdtexfcgvhbnjmk,l;';



